export { HostedRenderer } from "./hosted.js";
export { PluginRegistry, definePlugin } from "./plugins.js";
export type {
  VexaPlugin,
  PluginLifecycleContext,
  PluginSetupContext,
  PluginVideoOperationContext,
  PluginVideoOperationDefinition,
  PluginRenderBackendContext,
  PluginRenderBackendDefinition,
  PluginEncoderResolution,
  PluginEncoderProviderDefinition,
  PluginJobHandlerDefinition,
  PluginLoadOptions,
  PluginProgressUpdate,
  PluginBackendExecutionOptions
} from "./plugins.js";
export { JobQueue, JobHandle, DistributedJobQueue, DistributedJobWorker } from "./jobs.js";
export type { JobHandler, JobHandlerContext, JobHandlerOptions, JobProgressUpdate, LocalJobQueueOptions, JobListOptions, WaitForJobOptions, DistributedJobTransport, DistributedJobWorkerOptions } from "./jobs.js";
export { RedisJobTransport } from "./redis-jobs.js";
export type { RedisCommandClient, RedisJobTransportOptions } from "./redis-jobs.js";
export { Storage, MediaWorkspace, parseStorageSource } from "./storage.js";
export type { StorageAdapter, StorageAdapterHandlers, StorageOptions, ResolvedMediaSource } from "./storage.js";
export { Hardware } from "./hardware.js";
export { Streaming } from "./streaming.js";
export { Captions } from "./captions.js";
export { Audio } from "./audio.js";
export { VideoProject, createProject } from "./project.js";
export type { AddProjectTrackOptions, CreateVideoProjectOptions, UpdateProjectTrackOptions } from "./project.js";
export { Video } from "./video.js";
export type {
  HostedRenderState,
  HostedRenderRequest,
  HostedRenderProgress,
  HostedRenderArtifact,
  HostedRenderFailure,
  HostedRenderJob,
  HostedRenderCallOptions,
  HostedRenderWaitOptions,
  HostedRenderAdapter,
  PluginCapability,
  PluginLifecycleState,
  PluginDependency,
  PluginMetadata,
  PluginContributionCatalog,
  PluginCatalogEntry,
  PluginPackageManifest,
  PluginEncoderRequest,
  PluginEncoderSelection,
  JobState,
  JobTerminalState,
  JobRetryPolicy,
  JobRetryOptions,
  JobMetadataValue,
  JobSubmissionOptions,
  JobDescriptor,
  JobProgress,
  JobFailure,
  JobSnapshot,
  JobEventType,
  JobEvent,
  HardwareAccelerationPreference,
  HardwareAccelerationProvider,
  HardwareAccelerationOptions,
  HardwareAccelerationCapabilities,
  HardwareAccelerationDecision,
  HardwareDetectionOptions,
  HardwareBenchmarkOptions,
  HardwareBenchmarkResult,
  HardwareEncoderCapability,
  HardwareProviderCapability,
  HardwareVideoCodec,
  StorageProvider,
  ObjectStorageProvider,
  LocalMediaSource,
  HttpMediaSource,
  ObjectMediaSource,
  MediaStorageSource,
  StorageTransferOptions,
  HttpStorageOptions,
  StorageResolveOptions,
  StorageWorkspaceOptions,
  StorageTransferResult,
  StorageUploadResult,
  CaptionAnimation,
  CaptionCue,
  CaptionDocument,
  CaptionFormat,
  CaptionPosition,
  CaptionStyle,
  CaptionTemplateName,
  CaptionWordTiming,
  AudioChannelLayout,
  AudioDuckingOptions,
  AudioExecutionPlan,
  AudioExportOptions,
  AudioNormalizeOptions,
  AudioOperation,
  AudioCodec,
  AudioTimelineClip,
  BlendMode,
  ClipKind,
  ClipTransform,
  ClipTransitions,
  AudioStreamInfo,
  CodecDecision,
  CropOptions,
  EncoderPreset,
  ExecutionMode,
  ExecutionTask,
  ExportOptions,
  ExtractAudioOptions,
  MediaExecutionPlan,
  MediaOutputResult,
  MediaProgress,
  NumericKeyframe,
  NumericProperty,
  OutputContainer,
  ProjectCanvas,
  ProjectExecutionPlan,
  ProjectInputDescriptor,
  ProjectRenderOptions,
  ProjectTrack,
  ProjectTrackType,
  ProbeOptions,
  ProbeResult,
  SilenceDetectionOptions,
  SilenceDetectionResult,
  SilenceRange,
  ResizeFit,
  ResizeOptions,
  RotateOptions,
  TextStyle,
  TextTimelineClip,
  ThumbnailOptions,
  TimelineClip,
  TimelineClipBase,
  TransitionType,
  TrimOptions,
  VideoCodec,
  VideoLoadOptions,
  VideoProjectAst,
  VideoTimelineClip,
  ImageTimelineClip,
  KeyframeEasing,
  VideoOperation,
  VideoPipelineAst,
  VideoStreamInfo,
  WaveformOptions,
  StreamingProtocol,
  StreamingPresetName,
  HlsPlaylistType,
  StreamingRendition,
  StreamingPackageOptions,
  StreamingExecutionPlan,
  StreamingPackageResult,
  PreviewSpriteOptions,
  PreviewSpriteCue,
  PreviewSpritePlan,
  PreviewSpriteResult
} from "@vexa-video/core";
export {
  BinaryNotFoundError,
  HardwareAccelerationUnavailableError,
  InvalidCaptionError,
  IncompatibleOutputError,
  InvalidMediaSourceError,
  InvalidOperationError,
  InvalidProjectError,
  InvalidStreamingError,
  InvalidStorageError,
  InvalidPluginError,
  PluginNotFoundError,
  PluginConflictError,
  PluginDependencyError,
  PluginExecutionError,
  InvalidJobError,
  JobNotFoundError,
  JobCancelledError,
  JobExecutionError,
  JobIdempotencyConflictError,
  JobQueueClosedError,
  JobTransportError,
  RemoteMediaRejectedError,
  StorageAdapterNotFoundError,
  StorageTransferError,
  ProbeError,
  ProcessAbortedError,
  ProcessExecutionError,
  ProcessTimeoutError,
  VideoSdkError
} from "@vexa-video/core";
